/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:52ec937b-9063-442b-8bca-7d08c34d5319",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_nsAYcvGWy",
    "aws_user_pools_web_client_id": "68t8b6oe81rucpsim19fr836dr",
    "oauth": {}
};


export default awsmobile;
